package com.example.minami;

public class WordHelp {
    String[] cet4en = {"cube",
            "submerge",
            "credit",
            "surrounding",
            "stove",
            "submit",
            "carrier",
            "imply",
            "strain",
            "consist",
            "strap",
            "efficient",
            "accommodation",
            "strategic",
            "layer",
            "exclaim",
            "representative",
            "forecast",
            "discipline",
            "neutral",
            "interpret",
            "knot",
            "desirable",
            "promote",
            "acceptance",
            "mayor",
            "equation",
            "routine",
            "ripe",
            "prove",
            "likewise",
            "chap",
            "explore",
            "overnight",
            "strategy",
            "straw",
            "bind",
            "stream",
            "bearing",
            "suppose",
            "access",
            "remain",
            "abstract",
            "stretch",
            "approximate",
            "striking",
            "abuse",
            "critic",
            "interpretation",
            "string",
            "illustrate",
            "helpful",
            "leak",
            "accountant",
            "crude",
            "product",
            "strip",
            "stripe",
            "communicate",
            "following",
            "hedge",
            "consumer",
            "emotional",
            "craft",
            "institute",
            "indispensable",
            "scheme",
            "scale",
            "replace",
            "bark"};
    String[] cet4cn ={"立方体；立方",
            "浸没，潜入水中",
            "信贷，赊账；赞扬，荣誉；学分；信任",
            "周围的事物，环境",
            "炉，火炉，电炉",
            "屈从，听从，服从；呈送，提交；主张，建议",
            "运输工具，运载工具；带菌者；载重架，置物架",
            "暗示，意指",
            "拉紧；过劳；极度紧张；张力；扭伤，拉伤；旋律；品种，家系；气质，个性特点",
            "由…组成；在于；一致",
            "带子",
            "效率高的；有能力的",
            "住处，膳宿",
            "对全局有重要意义的，关键的；战略上的",
            "层，层次",
            "呼喊，惊叫",
            "代表，代理人",
            "预测，预报",
            "纪律；训练；惩罚；学科",
            "中立的，中性的",
            "解释，说明，口译",
            "（绳子的）结，（树的）节",
            "值得向往的；可取的",
            "促进，增进，发扬；提升；宣传，推销",
            "接受，承认；容忍",
            "市长",
            "方程式，等式",
            "例行公事，惯例，惯常的程序",
            "熟的，时机成熟的",
            "证明；结果是；证实",
            "同样地；也，又",
            "小伙子，男人，家伙",
            "探险，探索；仔细查阅，探究",
            "在整个夜里；在短时间内，突然",
            "战略，策略",
            "稻草；麦秆吸管，吸管",
            "捆绑，包扎，装订；约束；使结合，使黏合",
            "河，溪流；一股，一串",
            "举止，风度；方位，方向感；轴承",
            "猜想，假定，让",
            "接近；通道，入口",
            "剩下，余留，保持；仍然是",
            "抽象的，抽象派的",
            "伸展，延续；伸长，拉长；使倾注全力；使紧张",
            "近似的",
            "显著的，突出的；惹人注目的，容貌出众的",
            "滥用；虐待，伤害；辱骂，毁谤",
            "批评家，爱挑剔的人",
            "解释，口译",
            "线，细绳；一串，一行",
            "说明",
            "给予帮助的，有用的",
            "漏，泄露",
            "会计人员，会计师",
            "简陋的，天然的；粗鲁的，粗俗的",
            "产品，产物；乘积",
            "脱光衣服；剥夺，夺去",
            "条纹",
            "通讯，交际，交流；连接，相通；传达，传播；传染",
            "接着的，下列的",
            "篱笆，树篱，障碍物",
            "消费者，用户，消耗者",
            "感情的，情绪的",
            "工艺，手艺；船，航空器",
            "研究所，学院",
            "必不可少的，必需的",
            "计划，方案；阴谋",
            "大小，规模；等级，级别",
            "代替，取代；更换，调换；把…放回原处",
            "吠，叫"};

    public void setCet4cn(String[] cet4cn) {
        this.cet4cn = cet4cn;
    }

    public void setCet4en(String[] cet4en) {
        this.cet4en = cet4en;
    }

    public String[] getCet4en(){
        return cet4en;
    }

    public String[] getCet4cn(){
        return cet4cn;
    }
}
